//! Test text extraction from hello_world.pdf

use oxidize_pdf::parser::PdfReader;
use oxidize_pdf::text::TextExtractor;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Extract text from hello_world.pdf generated by our writer
    let document = PdfReader::open_document("hello_world.pdf")?;
    println!("✓ PDF parsed successfully!");

    // Try to extract text
    let extractor = TextExtractor::new();
    match extractor.extract_from_document(&document) {
        Ok(pages) => {
            println!("✓ Text extraction successful!");
            for (i, page) in pages.iter().enumerate() {
                println!("\nPage {}: {}", i + 1, page.text);
            }
        }
        Err(e) => {
            println!("✗ Text extraction failed: {e:?}");
        }
    }

    Ok(())
}
